apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsku-deploy
spec:
  selector:
    matchLabels:
      app-type: appsku
  template:
    metadata:
      labels:
        app-type: appsku
    spec:
      containers:
      - name: ct-appsku
        image: emirkipang/apps-2048
        ports:
        - containerPort: 80
